[pytest]
addopts = -vs
testpaths = testcase
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_file_level = INFO
log_file_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
markers =
    smoke: mark a test as a smoke test.
    regression: mark a test as a regression test.
    critical: mark a test as critical.
    debug: mark a test for debugging purposes.
